package promotion

import "fmt"

func (ps *PromotionService) Delete(promotionId string) error {
	clients, err := ps.tokenStorage.GetAll()
	if err != nil {
		return err
	}

	for _, cli := range clients {
		if cli.PromotionId == promotionId {
			return fmt.Errorf("there is some client generated by {%s}", promotionId)
		}
	}

	if err := ps.promotionRepo.Delete(promotionId); err != nil {
		return err
	}

	return nil
}
